
export class ProfileModel{
    org_ind_details_id: any;
    date: any;
    pt: any;
    city: any;
    mobileNumber:any;
    whatsAppNo: any;
    gst: any;
    tasc: any;
    // tid: any;
    maddress: any;
    pin: any;
    // customerId: any;
    mCity: any;
    mMobile: any;
    aadhaar: any;
    uin: any;
    pan: any;
    email: any;
    tan: any;
    address: any ;
    telephone: any;
    branchCode: any;
    mTelephone:any;
    name: any;
    aof: any;
    mpin: any;

// incorporationRegistrationDob: any;
    // tids: any;
    // applicantName: any;
    // pan_No: any;
    // aadhaarNo: any;
    // tanNo: any;
    // ptNo: any;
    // gstNo: any;
    // // uin: any;
    // tascNo: any;
    // emailId: any;
    // // address: any;
    // maAddress: any;
    // // city: any;
    // m_city: any;
    // // pin: any;
    // m_pin: any;
    // telephoneNo: any;
    // m_telephoneNo:any;
    // // mobileNumber: any;
    // m_mobileNumber: any;
    // // whatsAppNo: any; 
}